[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.7.5"
itertools = "0.13.0"
rand = "0.8.5"
rocket = {version = "0.5.1", features = ["json"]}
serde = "1.0.215"
